# on:
#   schedule:
#     - cron: '30 4,18 * * *'
#   workflow_dispatch:

# jobs:
#   run:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan github.com >> ~/.ssh/known_hosts

#       - name: Run Automation
#         run: |
#           # Switch remote from HTTPS to SSH so the bot can use the SSH Key
#           git remote set-url origin git@github.com:${{ github.repository }}.git
          
#           chmod +x auto-commiter
#           ./auto-commiter
#         env:
#           REPO_URL: git@github.com:${{ github.repository }}.git
#           SSH_KEY_PATH: ~/.ssh/id_rsa
